### ISSUE TITLE
The test network cannot create an account

### ISSUE THREAD

**Issue by drunken005** [meet-one/sidechain#2]
The test network cannot create an account？

http://35.236.182.224:6677/newaccount?name=kofo.ac

or

http://sidechain-test.meet.one:6677/newaccount?name=kofo.ac

How to fix it up?

**Comment by wuyahuang** [comment]
You can only create an new account end with .m, such as testnet112.m

http://34.80.195.33:6677/newaccount?name=testnet112.m

**Comment by drunken005** [comment]
Thanks!
