### ISSUE TITLE
How do I use snapshot recovery

### ISSUE THREAD

**Issue by drunken005** [meet-one/sidechain#3]
The snapshot list you provided is different from that of eos. How can I use your snapshot to synchronize

**Comment by wuyahuang** [comment]
nodeos --config-dir /ubuntu/nodeos/config-dir --data-dir /ubuntu/nodeos/data-dir --snapshot /ubuntu/nodeos/data-dir/snapshots/snapshot-xxxxxxxxxxxxxxxxxx.bin

**Comment by drunken005** [comment]
![image](https://user-images.githubusercontent.com/16334736/63335946-d8a5aa80-c370-11e9-8dfe-861d46104ca1.png)

**Comment by wuyahuang** [comment]
Please upgrade your nodeos to 1.8.1

**Comment by drunken005** [comment]
> nodeos --config-dir /ubuntu/nodeos/config-dir --data-dir /ubuntu/nodeos/data-dir --snapshot /ubuntu/nodeos/data-dir/snapshots/snapshot-xxxxxxxxxxxxxxxxxx.bin


download snapshot:
https://storage.googleapis.com/meetone-snapshot-backups/snapshot-01caf3cb43817a374d34c3dc167dff2fbb91c93a1147bbc1440cc33c8312882f.bin.gz

**Comment by drunken005** [comment]
> Please upgrade your nodeos to 1.8.1

ok thanks
